name: simcc
services:
  backend:
    depends_on:
      - postgres
      - pgadmin
    build:
      context: backend/
      target: dev
    env_file:
      - "backend/.env"
    expose:
      - "8080"
    ports:
      - "5005:5005"
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.simcc-backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.simcc-backend.loadbalancer.server.port=8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2

  frontend:
    depends_on:
      - traefik
      - backend
    build:
      context: frontend/
      target: dev
    expose:
      - "5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simcc-frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.simcc-frontend.loadbalancer.server.port=5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules


  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - "backend/.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    expose:
      - "80"
    environment:
      SCRIPT_NAME: /pgadmin
    env_file:
      - "./backend/.env"
    volumes:
      - pgadmin-store:/var/lib/pgadmin/
    depends_on:
      - postgres
    configs:
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=PathPrefix(`/pgadmin`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" 
    ports:
      - "7777:80"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "simcc",
            "Group": "Servers",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "simcc"
          }
        }
      }
volumes:
  postgres_data:
  pgadmin-store:
