services:
  backend:
    environment:
      ON_WINDOWS: 1
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://host.docker.internal:2375"
