FROM maven:3.9-eclipse-temurin-25 AS dev
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -q
EXPOSE 8080 5005
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
